pr: none
trigger:
  branches:
    include:
      - main

pool: pins-odt-agent-pool

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
      ref: 8d1a25431148c74269f4b6e72efd8fdf638bb5b2

extends:
  template: stages/wrapper_cd.yml@templates
  parameters:
    environments:
      - name: Dev
    deploymentStages:
      - name: Build & Deploy
        deploymentJobs:
          - name: Build & Deploy
            steps:
              - checkout: self
              - template: ../steps/azure_web_app_docker_build_push.yml@templates
                parameters:
                  azurecrName: pinscrsharedtoolinguks
                  dockerfilePath: $(Build.SourcesDirectory)/Dockerfile
                  repository: prototypes/appeals-back-office
              - template: ../steps/azure_web_app_deploy_slot.yml@templates
                parameters:
                  appName: pins-app-prototype-appeals-back-office-dkr
                  appResourceGroup: pins-rg-prototypes-dev
                  azurecrName: pinscrsharedtoolinguks
                  repository: prototypes/appeals-back-office
                  slot: default
                  gitCommitHash: $(Build.SourceVersion)